### ISSUE TITLE
As a Site User I can access a navbar from every page so that I can navigate the site easily

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#1]
EPIC: Navigation

USER STORY: As a **Site User** I can **access a navbar from every page** so that **I can navigate the site easily**

**Acceptance Criteria:**
- [x] Nav bar is present on all pages
- [x] Navbar can be used for navigation

**Tasks**
- [x] Create NavBar component
- [x] Add component to App.js
- [x] Install react-router-dom to handle routing
- [x] Add routing
- [x] Add links to the NavBar component
