### ISSUE TITLE
As a Site User I can view a feed of posts so that I can get the latest content

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#10]
EPIC: View posts

USER STORY: As a **Site User** I can **view a feed of posts** so that **I can get the latest content**

**Acceptance Criteria:**
- [x] When on the homepage a feed of posts are loaded

**Tasks**
- [x] Create a component to display the posts
- [x] Add Route
- [x] Write logic to fetch posts
