### ISSUE TITLE
As a Site User I can view posts I have liked so that I can find my way back to them easily

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#11]
EPIC: View posts

USER STORY: As a **Site User** I can **view posts I have liked** so that **I can find my way back to them easily**

**Acceptance Criteria:**
- [x] On the liked posts page I can see posts I have liked

**Tasks**
- [x] In App.js check for the current user
- [x] Add filter to the route
- [x] In the function to get posts, set a filter
