### ISSUE TITLE
As a Site User I can search for posts so that I can find content I'm looking for

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#12]
EPIC: Search

USER STORY: As a **Site User** I can **search for posts** so that **I can find content I'm looking for**

**Acceptance Criteria:**
- [x] A search bar exists
- [x] Typing in the search bar will return results based on
- [x] User, tags or title

**Tasks**
- [x] Add a search bar
- [x] Add a handler to control that users only need to type in the search bar to return results
- [x] Add query value to the API request
