### ISSUE TITLE
As a Site User I can delete my post so that I can remove it if I want

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#14]
EPIC: Delete post

USER STORY: As a **Site User** I can **delete my post** so that **I can remove it if I want**

**Acceptance Criteria:**
- [x] A signed in user can delete their own posts
- [x] The should be a confirmation before the post is deleted

**Tasks**
- [x] Add confirmation dialogue when Delete Post is clicked
- [x] Define function to handle delete
- [x] Pass the delete function to the dropdown toggle
