### ISSUE TITLE
Site User I can edit my post so that I can change it if I want to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#15]
EPIC: Edit Post

USER STORY: As a **Site User** I can **edit my post** so that **I can change it if I want to**

**Acceptance Criteria:**
- [x] When viewing a post as the owner, I can choose to edit the post
- [x] When clicking edit post, I get taken to a form that is pre-filled with the post data
- [x] When submitting the updated data, my post is updated

**Tasks**
- [x] Copy code from PostCreateForm since they will be very similar
- [x] Add route
- [x] Add function to handle the API request
- [x] Update post method to put method
- [x] Clean up unneeded code used in the copied code
