### ISSUE TITLE
As a Site User I can add comments to a post so that I can engage with the community

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#16]
EPIC: Add Comments

USER STORY: As a **Site User** I can **add comments to a post** so that **I can engage with the community**

**Acceptance Criteria:**
- [x] A signed in user can add comments to a post
- [x] A signed out user can not add comments

**Tasks**
- [x] Create a form to add comments
- [x] Add function to handle form input
- [x] Add function to handle form submission
