### ISSUE TITLE
As a Site User I can view comments so that I can read what other users think of the post

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#17]
EPIC: View comments

USER STORY: As a **Site User** I can **view comments** so that **I can read what other users think of the post**

**Acceptance Criteria:**
- [x] When a user is viewing a post, they can also see comments

**Tasks**
- [x] Add comment component
- [x] Add API request to get comments
- [x] Add conditional rendering
