### ISSUE TITLE
As a Site User I can delete my comments so that I can remove them if I want to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#18]
EPIC: Delete comment

USER STORY: As a **Site User** I can **delete my comments** so that **I can remove them if I want to**

**Acceptance Criteria:**
- [x] When a user views their comment, they have the option to delete it
- [x] Deleting a comment decrements the comments count by 1
- [x] Deleting a comment removes the comment

**Tasks**
- [x] Add dropdown menu with a delete option for signed in user
- [x] Add function to handle delete
- [x] Make sure comment count is decremented
