### ISSUE TITLE
As a Site User I can edit my comments so that I can change them if I want to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#19]
EPIC: Edit Comments

USER STORY: As a **Site User** I can **edit my comments** so that **I can change them if I want to**

**Acceptance Criteria:**
- [x] A user can choose to edit their comments
- [x] When they choose to do so, they are presented with their comment content pre-filled
- [x] When submitted, the comment is updated

**Tasks**
- [x] Create an edit form form component
- [x] Make sure it is populated by its former content
- [x] Write function to handle the form submission
