### ISSUE TITLE
As a Site User I can register an account so that I can access more features

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#2]
EPIC: Authentication

USER STORY: As a **Site User** I can **register an account** so that **I can access more features**

**Acceptance Criteria:**
- [x] I can access the page to register an account.
- [x] There is a form that I can use to sign up.
- [x] The form creates an account when submitted.

**Tasks**
- [x] Connect to backend API
- [x] Create a form where user can register
- [x] Add form to Route
- [x] Handle form events and errors
