### ISSUE TITLE
As a Site User I can create albums so that I can get organized

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#20]
EPIC: Create Albums

USER STORY: As a **Site User** I can **create albums** so that **I can get organized**

**Acceptance Criteria:**
- [x] User can fill out a form to create albums
- [x] The creation form should be on the same page as the albums are listed

**Tasks**
- [x] Create form for album creation
- [x] Create album list page and add album creation form to it
- [x] Add function to handle album creation
