### ISSUE TITLE
As a Site User I can view my albums so that I can interact with them

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#21]
EPIC: View Albums

USER STORY: As a **Site User** I can **view my albums** so that **I can interact with them**

**Acceptance Criteria:**
- [x] When navigating to Albums the user can see their albums

**Tasks**
- [x] Add JSX where Album can be displayed
- [x] Add function to request albums from API
- [x] Add function to display Albums
