### ISSUE TITLE
As a Site User I can like comments so that I can show people I liked what they said

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#22]
EPIC: Like comments

USER STORY: As a **Site User** I can **like comments** so that **I can show people I liked what they said**

**Acceptance Criteria:**
- [x] A signed in user can like a comment
- [x] A signed out user cannot like a comment
- [x] When a user creates a like, likes count go up

**Tasks**
- [x] Add JSX do display likes
- [x] Add function to handle likes
- [x] Render likes conditionally
