### ISSUE TITLE
As a Site User I can unlike a comment so that I can change my mind

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#23]
EPIC: Like Comments

USER STORY: As a **Site User** I can **unlike a comment** so that **I can change my mind**

**Acceptance Criteria:**
- [x] When a user has liked a comment, they can click it again to unlike

**Tasks**
- [x] Create function to unlike a comment
- [x] Make sure like count decrements
