### ISSUE TITLE
As a Site User I can delete my albums so that I can remove them if I want to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#24]
EPIC: Delete Album

USER STORY: As a **Site User** I can **delete my albums** so that **I can remove them if I want to**

**Acceptance Criteria:**
- [x] A user is able to delete albums they have created

**Tasks**
- [x] Add dropdown toggle and display delete choice
- [x] Add function to handle delete
- [x] Update state
