### ISSUE TITLE
As a Site User I can edit my albums so that I can change their names if I want to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#25]
EPIC: Edit Albums

USER STORY: As a **Site User** I can **edit my albums** so that **I can change their names if I want to**

**Acceptance Criteria:**
- [x] Users are able to edit the title of their albums

**Tasks**
- [x] Add a form for editing albums
- [x] Display form when user chooses to edit a form
- [x] Write function to handle form submission
