### ISSUE TITLE
As a Site User I can add posts to albums so that I can sort content as I want to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#26]
EPIC: Add posts to albums

USER STORY: As a **Site User** I can **add posts to albums** so that **I can sort content as I want to**

**Acceptance Criteria:**
- [x] When a user is viewing a post, they can choose to add it to an album
- [x] The user must first have created the album

**Tasks**
- [x] Create a form where the user can choose to add post to an existing album
- [x] Write function to get the users albums and display them in the form
- [x] Write function to handle form submission
