### ISSUE TITLE
As a Site User I can view posts I have added to my albums so that I can find the posts I want

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#27]
EPIC: View posts in albums

USER STORY: As a **Site User** I can **view posts I have added to my albums** so that **I can find the posts I want**

**Acceptance Criteria:**
- [x] If a user has albums with posts added
- [x] They can click their albums to view the posts

**Tasks**
- [x] Add layout
- [x] Create function to get posts in album detail
- [x] Add function to display the posts that belong to the album
