### ISSUE TITLE
As a Site User I can visit other users profiles so that I can learn more about them

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#28]
EPIC: User Profile

USER STORY: As a **Site User** I can **visit other users profiles** so that **I can learn more about them**

**Acceptance Criteria:**
- [x] When visiting a users profile their profile image is visible
- [x] When visiting a users profile there is a field where I can read about the profile owner if they have added anything
- [x] Their username is displayed

**Tasks**
- [x] Create a profile page
- [x] Create function to get profile data
- [x] Display the fetched data
