### ISSUE TITLE
As a Site User I can edit my profile so that I can change what users see about me

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#29]
EPIC: User Profile

USER STORY: As a **Site User** I can **edit my profile** so that **I can change what users see about me**

**Acceptance Criteria:**
- [x] Owner of the profile has a dropdown menu where they can choose to edit
- [x] When clicked, they get a form where information can be edited
- [x] When form is submitted, their profile is updated

**Tasks**
- [x] Add a dropdown menu for profile owner
- [x] Add a form for editing profile
- [x] Add function to fetch profile information
- [x] Add function to handle form submission
