### ISSUE TITLE
As a Site User I can sign in so that I get access to additional features

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#3]
EPIC: Authentication

USER STORY: As a **Site User** I can **sign in** so that **I get access to additional features**

**Acceptance Criteria:**
- [x] Sign in page is accessible
- [x] Sign in page has a form to sign in
- [x] A registered user can sign in

**Tasks**
- [x] Create a sign in form with username and password
- [x] Add Route
- [x] Handle form events and errors
