### ISSUE TITLE
As a Site User I can delete my profile so that I can remove it if I want to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#30]
EPIC: User Profile

USER STORY: As a **Site User** I can **delete my profile** so that **I can remove it if I want to**

**Acceptance Criteria:**
- [ ] A user can choose to delete their profile
- [ ] There should be a delete confirmation
- [ ] Only the owner can delete it

**Tasks**
- [ ] Add function to delete profile if the user owns it
- [ ] Add confirmation modal
