### ISSUE TITLE
As a Site User I can see my logged in status so that I can log out if I need to

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#4]
EPIC: Authentication

USER STORY: As a **Site User** I can **see my logged in status** so that **I can log out if I need to**

**Acceptance Criteria:**
- [x] When I am logged in it is reflected with my name in the navbar
- [x] I get access to additional links

**Tasks**
- [x] Create context hook, to not have to pass user state down component tree as props
- [x] Request user from API
- [x] Conditionally render icons in navbar depending on logged in state
