### ISSUE TITLE
As a Site User I can remain logged in for some time, or until I log out so that I have a good experience

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#5]
EPIC: Authentication

USER STORY: As a **Site User** I can **remain logged in for some time, or until I log out** so that **I have a good experience**

**Acceptance Criteria:**
- [x] After signing in, I stay signed in until I sign out.

**Tasks**
- [x] Create axios interceptors
- [x] One for requests
- [x] And one for responses
