### ISSUE TITLE
As a Site User I can add posts so that I can share my content

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#6]
EPIC: Add posts

USER STORY: As a **Site User** I can **add posts** so that **I can share my content**

**Acceptance Criteria:**
- [x] I can access Add Post when logged in
- [x] Add Post has a form to create a post
- [x] When the form is submitted my post is created

**Tasks**
- [x] Create the form to handle adding posts
- [x] Add handling of form submission logic
- [x] Add error handling
- [x] Redirect the user to their newly created post
