### ISSUE TITLE
As a Site User I can view a single post so that I can interact with it

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#7]
EPIC: View post

USER STORY: As a **Site User** I can **view a single post** so that **I can interact with it**

**Acceptance Criteria:**
- [x] When visiting the URL of a post I can view it

**Tasks**
- [x] Create post page component
- [x] Add route
- [x] Write function to retrieve post from the API
- [x] Display the retrieved data
