### ISSUE TITLE
As a Site User I can like a post so that I can show appreciation

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#8]
EPIC: Like posts

USER STORY: As a **Site User** I can **like a post** so that **I can show appreciation**

**Acceptance Criteria:**
- [x] When viewing a post I can like it
- [x] If I change my min and click it again the pust will be unliked

**Tasks**
- [x] Display a button to click
- [x] Conditionally render depending on user state
- [x] Add logic to handle liking a post
- [x] Add logic to handle un-liking a post
