### ISSUE TITLE
As a Site User I can download a post image so that I can keep it for later

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/snaps#9]
EPIC: Download post image

USER STORY: As a **Site User** I can **download a post image** so that **I can keep it for later**

**Acceptance Criteria:**
- [x] When viewing a post there is a download button
- [x] The button takes me to a page where I can download the image
- [x] Download count is incremented

**Tasks**
- [x] Add icon and link to the image URL
- [x] Write function to increment download count when button is clicked
